project:
  type: website

website:
  title: "Gaussian integral"
  navbar:
    left:
      - href: gaussian-integral.qmd
        text: "Gaussian integral"
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Topics"
        contents:
          - text: "Gaussian integral"
            href: gaussian-integral.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
    toc-title: "On This Page"
